config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  get 'about' => "home#about"

  root 'home#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
    belongs_to :user
    has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150>" }, default_url: "/image/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :pin_owner]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :pin_owner, only: [:edit, :update, :destroy]
  
   # add this method                         
    def pin_owner
     unless @pin.user_id == current_user.id
      flash[:notice] = 'Access denied as you are not owner of this Job'
      redirect_to pins_path
     end
    end
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<% if user_signed_in? %>
  <% gravatar_id = Digest::MD5.hexdigest(current_user.email.downcase) %>
  <% avatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=40" %>
<% end %>
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Pinterested', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_url %></li>
        <li><%= link_to "About", about_url %></li>
        <% if user_signed_in? %>
          <li class = 'dropdown'>
            <%= link_to pins_url, class: "dropdown-toggle", data: {toggle: 'dropdown'} do %>
              Post
              <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to 'Manage Post',pins_path %></li>
              <li><%= link_to 'New Post', new_pin_path %></li>
            </ul>
          </li>
          <li class='dropdown'>
            <%= link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'} do %>
            <%= image_tag avatar_url %>
            <%= current_user.email %> <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete%></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Join", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About me</h1>
<p>My name is MH Raihan and I'm building a Pinterested clone website</p>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Welcome to my pinterested App</h1>
  <p>pretty cool, eh?</p>
  <div class="userinfo text-center">
    <% if user_signed_in? %>
      <p>Hi, <%= current_user.email %></p>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-warning' %>
    <%else%>
      <%= link_to "Login", new_user_session_path, class:"btn btn-default" %>
      <%= link_to "Join", new_user_registration_path, class:"btn btn-primary" %>
    <%end%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'home/header' %>
<div class="container">
<div class="div_notice">
  <% flash.each do |name,msg| %>
    <%= content_tag(:div, msg, class: 'alert alert-info') %>
  <% end %>
</div>
  <%= yield %>
</div>

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true} do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", style: "width: 100%; height: 330px;" %>
  </div>
    <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-default" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Editing Pin</h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
   <div class="panel-footer"><%= link_to 'Show', @pin %> |
    <%= link_to 'Back', pins_path %></div>
</div>

app/views/pins/index.html.erb
<h1>Listing Pins</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Thumb</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= image_tag pin.image.url(:thumb) %></td>
        <td><%= pin.description %></td>
        <td><%= link_to 'Show', pin, class: "btn btn-info" %></td>
        <% if current_user == pin.user %>
          <td><%= link_to 'Edit', edit_pin_path(pin), class: "btn btn-warning" %></td>
          <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Pin', new_pin_path,class: "btn btn-primary btn-lg btn-block" %>
<% end %>

app/views/pins/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New Pin</h3>
  </div>
  <div class="panel-body">
      <%= render 'form' %>
  </div>
   <div class="panel-footer"><%= link_to 'Back', pins_path %></div>
</div>

app/views/pins/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Description</h3>
  </div>
  <div class="panel-body">
    <p><%= image_tag @pin.image.url(:large) %></p>
    <p><%= @pin.description %></p>
  </div>
   <div class="panel-footer">
     <% if current_user == @pin.user %>
       <%= link_to 'Edit', edit_pin_path(@pin) %> |
     <% end %>
       <%= link_to 'Back', pins_path %>
   </div>
</div>